--
-- PostgreSQL database dump
--

-- Dumped from database version 11.1
-- Dumped by pg_dump version 11.1

-- Started on 2019-02-02 05:38:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 197 (class 1259 OID 32780)
-- Name: expenses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expenses (
    id integer NOT NULL,
    amount numeric NOT NULL,
    payee text NOT NULL,
    category text,
    account text,
    date timestamp without time zone,
    repeat boolean,
    memo text,
    impulse boolean,
    colorcode text
);


ALTER TABLE public.expenses OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 32778)
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2810 (class 0 OID 32780)
-- Dependencies: 197
-- Data for Name: expenses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expenses (id, amount, payee, category, account, date, repeat, memo, impulse, colorcode) FROM stdin;
1	1	Gas Station	Other	First Interstate	2019-02-02 00:00:00	f	fill up rabbit	f	blue
\.


--
-- TOC entry 2816 (class 0 OID 0)
-- Dependencies: 196
-- Name: expenses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expenses_id_seq', 1, true);


--
-- TOC entry 2687 (class 2606 OID 32787)
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


-- Completed on 2019-02-02 05:38:28

--
-- PostgreSQL database dump complete
--

